require: 
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
   NewCops: enable
   Exclude:
     - 'node_modules/**/*'
     - 'vendor/**/*'
     - 'bin/*'
     - 'log/**/*'
     - 'public/**/*'
     - 'tmp/**/*'
     - '.git/**/*'
     - 'storage/**/*'
     - 'lib/**/*'
     - db/schema.rb
     - Guardfile

Rails/AddColumnIndex:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Exclude:
    - 'db/migrate/*'
