# Darkcoin Dash was originally released as XCoin (XCO
ltc:
  iso_code: LTC
  name: Litecoin
  symbol: Ł
  alternate_symbols: []
  subunit: litoshis
  # Source: https://en.wikipedia.org/wiki/Litecoin
  subunit_to_unit: 100000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

rub:
  iso_code: RUB
  name: Russian Ruble
  symbol: "₽"
  alternate_symbols:
  - руб.
  - р.
  subunit: Kopeck
  subunit_to_unit: 100
  symbol_first: false
  html_entity: "&#x20BD;"
  decimal_mark: ","
  thousands_separator: "."
  iso_numeric: '643'
  smallest_denomination: 1
  is_crypto: false

dsh:
  iso_code: DSH
  name: Dash
  symbol:
  alternate_symbols: []
  subunit:
  # Как у BTC, потому что это форл BTC
  subunit_to_unit: 100000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  authorized_round: 6
  is_crypto: true

kzt:
  iso_code: KZT
  name: Казахстанский Тэнге
  symbol: "₸"
  alternate_symbols: []
  subunit: Tiyn
  subunit_to_unit: 100
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '398'
  is_crypto: false
  smallest_denomination: 1

xrp:
  iso_code: XRP
  name: Ripple
  symbol:
  alternate_symbols: []
  subunit: drop
  # 1/миллионная- https://en.wikipedia.org/wiki/Ripple_(payment_protocol)
  subunit_to_unit: 1000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  authorized_round: 6
  is_crypto: true

etc:
  iso_code: ETC
  name: Ethereum Classic
  symbol:
  alternate_symbols: []
  subunit:
  # Как у Эфира, потому что это форк эфира
  subunit_to_unit: 1000000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  authorized_round: 6
  is_crypto: true

xmr:
  iso_code: XMR
  name: Monero
  symbol: ɱ
  alternate_symbols: []
  subunit: piconero
  subunit_to_unit: 1000000000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  authorized_round: 6
  is_crypto: true

bch:
  iso_code: BCH
  name: Bitcoin Cash
  symbol:
  alternate_symbols: []
  subunit:
  # Как биткойн, потому что это форк
  subunit_to_unit: 100000000
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  authorized_round: 8
  is_crypto: true

neo:
  iso_code: NEO
  name: Neo
  symbol: N
  alternate_symbols: []
  subunit: Neo
  subunit_to_unit: 1
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

zec:
  iso_code: ZEC
  name: Zcash
  symbol: Z
  alternate_symbols: []
  subunit: Zcash Cent
  subunit_to_unit: 100000000
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

uah:
  iso_code: UAH
  name: Ukrainian hryvnia
  symbol: "₴"
  alternate_symbols:
  - грн.
  subunit: Kopiyka
  subunit_to_unit: 100
  symbol_first: false
  html_entity: "&#x20B4;"
  decimal_mark: ","
  thousands_separator: "."
  iso_numeric: '4217'
  smallest_denomination: 1
  is_crypto: false

eos:
  iso_code: EOS
  name: Eos
  symbol:
  alternate_symbols: []
  subunit: Larimer
  subunit_to_unit: 10000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

ada:
  iso_code: ADA
  name: Cardano
  symbol:
  alternate_symbols: []
  subunit: lovelaces
  subunit_to_unit: 1000000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

xem:
  iso_code: XEM
  name: XEM
  symbol:
  alternate_symbols: []
  subunit: microXEM
  subunit_to_unit: 1000000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

waves:
  iso_code: WAVES
  name: Waves
  symbol:
  alternate_symbols: []
  subunit: Wavelet
  subunit_to_unit: 100000000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

trx:
  iso_code: TRX
  name: Tron
  symbol:
  alternate_symbols: []
  subunit: Sun
  subunit_to_unit: 1000000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

doge:
  iso_code: DOGE
  name: Dogecoin
  symbol: Ð
  alternate_symbols: []
  subunit: Microdoge
  subunit_to_unit: 1000000
  symbol_first: true
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true
