---
btc:
  iso_code: BTC
  name: Bitcoin
  symbol: B⃦
  alternate_symbols: []
  subunit: Satoshi
  subunit_to_unit: 100000000
  symbol_first: false
  html_entity: "&#x20bf;"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  is_crypto: true

eth:
  iso_code: ETH
  name: Ethereum
  symbol: Ξ
  alternate_symbols: []
  subunit: Gwei
  # может быть 10−18 степени, но мы останавливаемся на Gwey
  # https://en.wikipedia.org/wiki/Ethereum
  subunit_to_unit: 1_000_000_000
  base_factor: 18
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: ''
  smallest_denomination: 1
  blockchain_key: 'eth-mainnet'

usdt-erc20:
  iso_code: USDT-erc20
  native_currency: eth
  name: USDT(ERC20)
  subunit: USDT Cent
  subunit_to_unit: 100000
  base_factor: 6
  contract_address: '0xdac17f958d2ee523a2206206994597c13d831ec7'
  blockchain_key: 'eth-mainnet'
