production:
  order_limit: 200
  daily_limit: 500
  weekly_limit: 1000
sandbox:
  order_limit: 200
  daily_limit: 500
  weekly_limit: 1000
staging:
  order_limit: 200
  daily_limit: 500
  weekly_limit: 1000
test:
  order_limit: 200
  daily_limit: 500
  weekly_limit: 1000
development:
  order_limit: 200
  daily_limit: 500
  weekly_limit: 1000
