- id:                     usd
  name:                   US Dollar
  subunits:               2
  type:                   fiat
  precision:              2
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  min_deposit_amount:     0
  min_collection_amount:  0
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200
  deposit_fee:            0
  withdraw_fee:           0
  position:               1
  options:                {}
  blockchain_key: bitzlato

- id:                     btc
  subunits:               8
  name:                   Bitcoin
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_deposit_amount:     0.0000356
  min_collection_amount:  0.0000356
  withdraw_limit_24h:     0.1
  withdraw_limit_72h:     0.2
  deposit_fee:            0
  withdraw_fee:           0
  position:               2
  options:                {}
  blockchain_key: bitzlato

- id:                     eth
  name:                   Ethereum
  subunits:               18
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_deposit_amount:     0.00021
  min_collection_amount:  0.00021
  withdraw_limit_24h:     0.2
  withdraw_limit_72h:     0.5
  deposit_fee:            0
  withdraw_fee:           0
  position:               3
  blockchain_key: bitzlato
  options:
    # ETH tx fees configurations.
    #
    # Maximum amount of gas you're willing to spend on a particular transaction.
    gas_limit: 21_000
    # Internal price that is paid for running a transaction on the Ethereum network.
    gas_price: 1_000_000_000

- id:                     trst
  name:                   WeTrust
  parent_id:              eth
  contract_address:       '0x0000000000000000000000000000000000000000'
  type:                   coin
  visible:                true
  subunits:               6
  deposit_enabled:        true
  withdrawal_enabled:     true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  # NOTE: Network fee is paid in ETH but min_deposit_amount is in TRST.
  min_deposit_amount:     2
  min_collection_amount:  2
  withdraw_limit_24h:     300
  withdraw_limit_72h:     600
  deposit_fee:            0
  withdraw_fee:           0
  position:               4
  blockchain_key: eth-rinkeby
  options:
    # ERC20 tx fees configurations.
    #
    # Maximum amount of gas you're willing to spend on a particular transaction.
    gas_limit: 90_000
    # Internal price that is paid for running a contract on the Ethereum network.
    gas_price: 1_000_000_000
    #
    # ERC20 configuration.
    erc20_contract_address: '0x0000000000000000000000000000000000000000' # Always wrap this value in quotes!
