- id:                     usd
  name:                   US Dollar
  type:                   fiat
  precision:              2
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  min_collection_amount:  0
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200
  deposit_fee:            0
  position:               1
  options:                {}

- id:                     btc
  name:                   Bitcoin
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_collection_amount:  0.0000356
  withdraw_limit_24h:     0.1
  withdraw_limit_72h:     0.2
  deposit_fee:            0
  position:               2
  options:                {}

- id:                     eth
  name:                   Ethereum
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_collection_amount:  0.00021
  withdraw_limit_24h:     0.2
  withdraw_limit_72h:     0.5
  deposit_fee:            0
  position:               3
  options:
    # Internal price that is paid for running a transaction on the Ethereum network.
    gas_price: 1_000_000_000

- id:                     trst
  name:                   WeTrust
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  min_collection_amount:  2
  withdraw_limit_24h:     300
  withdraw_limit_72h:     600
  deposit_fee:            0
  position:               4
  options:
    # Internal price that is paid for running a contract on the Ethereum network.
    gas_price: 1_000_000_000

- id:                     bnb-bep20
  name:                   BNB-BEP20
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  min_collection_amount:  0.00021
  withdraw_limit_24h:     0.2
  withdraw_limit_72h:     0.5
  deposit_fee:            0
  position:               5
  options:
    # Internal price that is paid for running a transaction on the Ethereum network.
    gas_price: 1_000_000_000

- id:                     usdt-bep20
  name:                   USDT-BEP20
  type:                   coin
  visible:                true
  deposit_enabled:        true
  withdrawal_enabled:     true
  min_collection_amount:  0.00021
  withdraw_limit_24h:     0.2
  withdraw_limit_72h:     0.5
  deposit_fee:            0
  position:               6
  options:
    # Internal price that is paid for running a transaction on the Ethereum network.
    gas_price: 1_000_000_000