- name:              peatio-default-engine
  driver:            peatio
  state:             online
- name:              local-finex-spot-engine
  driver:            finex-spot
  state:             online
- name:              opendax-finex-spote-engine
  driver:            opendax
  uid:               U123456789
  url:               https://www.opendax.io/api/v2/finex
  key:               ""
  secret:            ""
  data:              {}
  # The data field for store some special engines metadata
  # Can be used in upstream worker
  # Example for upstream:
  #                {
  #                 "rest"=>"https://url",
  #                 "websocket"=>"wss://url",
  #                 "trade_proxy"=>true,
  #                 "orderbook_proxy"=>"true"
  #                }
  # }
  state:             online