- id:                btcusdt
  base_unit:         btc
  quote_unit:        usdt
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          100
  state:             enabled
  data:              {}

- id:                btcmcr
  base_unit:         btc
  quote_unit:        mcr
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          101
  state:             enabled
  data:              {}

- id:                ethbtc
  base_unit:         eth
  quote_unit:        btc
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          102
  state:             enabled
  data:              {}

- id:                ethusdt
  base_unit:         eth
  quote_unit:        usdt
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          103
  state:             enabled
  data:              {}

- id:                ethmcr
  base_unit:         eth
  quote_unit:        mcr
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          104
  state:             enabled
  data:              {}

- id:                usdtmcr
  base_unit:         usdt
  quote_unit:        mcr
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          105
  state:             enabled
  data:              {}

