- id:
  base_unit:         btc
  quote_unit:        usd
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          100
  state:             enabled
  data:              {}

- id:
  base_unit:         eth
  quote_unit:        usd
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          101
  state:             enabled
  data:              {}

- id:
  base_unit:         trst
  quote_unit:        usd
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          102
  state:             enabled
  data:              {}

- id:
  base_unit:         eth
  quote_unit:        btc
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          103
  state:             enabled
  data:              {}

- id:
  base_unit:         trst
  quote_unit:        btc
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          104
  state:             enabled
  data:              {}

- id:
  base_unit:         trst
  quote_unit:        eth
  engine_name:       peatio-default-engine
  amount_precision:  4
  price_precision:   4
  min_price:         0.0001
  max_price:         0.0
  min_amount:        0.0001
  position:          105
  state:             enabled
  data:              {}