- name:             Ethereum Deposit Wallet
  blockchain_key:   eth-ropsten
  currency_ids:     eth,trst
  # Address where deposits will be collected to.
  address:          '0x2b9fBC10EbAeEc28a8Fc10069C0BC29E45eBEB9C'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit  # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      0.0
  status:           active
  settings:
    #
    # Geth gateway client settings.
    uri:          http://127.0.0.1:8545
    secret:       'changeme'

- name:             Ethereum Hot Wallet
  blockchain_key:   eth-ropsten
  currency_ids:     eth,trst
  # Address where deposits will be collected to.
  address:          '0x270704935783087a01c7a28d8f2d8f01670c8050'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      100.0
  status:           active
  settings:
    #
    # Geth gateway client settings.
    uri:          http://127.0.0.1:8545
    secret:       'test'

- name:             Ethereum Warm Wallet
  blockchain_key:   eth-ropsten
  currency_ids:     eth,trst
  # Address where deposits will be collected to.
  address:          '0x2b9fBC10EbAeEc28a8Fc10069C0BC29E45eBEB9C'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      1000.0
  status:           active
  settings:
    #
    # Geth gateway client settings.
    uri:          http://127.0.0.1:8545
    secret:       'test'

- name:             Ethereum Wallet for paying ERC20 fees
  blockchain_key:   eth-ropsten
  currency_ids:     eth
  # Address where deposits will be collected to.
  address:          '0x270704935783087a01c7a28d8f2d8f01670c8050'  # IMPORTANT: Always wrap this value in quotes!
  kind:             fee  # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      100.0
  status:           active
  settings:
    #
    # Geth gateway client settings.
    uri:          http://127.0.0.1:8545
    secret:       'test'

- name:             Bitcoin Deposit Wallet
  blockchain_key:   btc-testnet
  currency_ids:     btc
  # Address where deposits will be collected to.
  address:          '2N4qYjye5yENLEkz4UkLFxzPaxJatF3kRwf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit   # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      0.0
  status:           active
  settings:
    #
    # Bitcoind gateway client settings.
    uri:          http://user:password@127.0.0.1:18332

- name:             Bitcoin Hot Wallet
  blockchain_key:   btc-testnet
  currency_ids:     btc
  # Address where deposits will be collected to.
  address:          '2N4qYjye5yENLEkz4UkLFxzPaxJatF3kRwf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot       # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      0.0
  status:           active
  settings:
    #
    # Bitcoind gateway client settings.
    uri:          http://user:password@127.0.0.1:18332
    # skip_deposit_collection - defines if deposit will be collected to
    # this wallet. Supported values: true | false. By default `false`.
    skip_deposit_collection: true

- name:             Bitcoin Warm Wallet
  blockchain_key:   btc-testnet
  currency_ids:     btc
  # Address where deposits will be collected to.
  address:          '2N4qYjye5yENLEkz4UkLFxzPaxJatF3kRwf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm      # Wallet kind (deposit, hot, warm, cold or fee).
  balance:          {}
  max_balance:      0.0
  status:           active
  settings:
    #
    # Bitcoind gateway client settings.
    uri:          http://user:password@127.0.0.1:18332

- name:             BSC Deposit
  blockchain_key:   bsc-testnet
  currency_ids:     bnb-bep20,usdt-bep20
  kind:             deposit
  status:           active
  settings:
    uri: http://127.0.0.1:8545
